//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarConfigurator.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ID { get; set; }
        public Nullable<int> ID_Car { get; set; }
        public string User { get; set; }
        public Nullable<int> ID_option { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Option Option { get; set; }
    }
}
