//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarConfigurator.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarConfiguratorEntities : DbContext
    {
        public CarConfiguratorEntities()
            : base("name=CarConfiguratorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Conf_type> Conf_type { get; set; }
        public virtual DbSet<Config> Config { get; set; }
        public virtual DbSet<Connections> Connections { get; set; }
        public virtual DbSet<Option> Option { get; set; }
        public virtual DbSet<Option_type> Option_type { get; set; }
    }
}
